sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.m2

notification:
  email:
    recipients:
      - edp_support@groups.163.com
    on_failure: always

branches:
  only:
    - master
