title: Davinci 用户手册
zh_masthead_title: 用户手册
baseurl: "/davinci"
logo: "assets/images/logo.svg"

# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.16.5"
markdown: kramdown
minimal_mistakes_skin: "default"
plugins:
  - jekyll-feed
  - jekyll-include-cache

collections:
  docs:
    permalink: /:collection/:path
    output: true

DAVINCI_VERSION: 0.3
DAVINCI_VERSION_SHORT: 0.3
